---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-quay
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: project-quay
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: quay
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- with .Values.app.selectorLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
      {{- with .Values.app.selectorLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      volumes:
        - name: configvolume
          secret:
            secretName: quay-enterprise-config-secret
      containers:
        - name: project-quay
          image: image-registry.openshift-image-registry.svc:5000/project-quay/project-quay:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8443
          volumeMounts:
            - name: configvolume
              readOnly: false
              mountPath: /conf/stack

