apiVersion: v1
kind: Secret
metadata:
  name: quay-enterprise-config-secret
  labels:
  {{- with .Values.app.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{ ( .Files.Glob "config/*" ).AsSecrets | indent 2 }}
